plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    // Approach #1: Ensure fabric-permissions-api is always available by including it within your own jar (it's only ~12KB!)
    //include(implementation('me.lucko:fabric-permissions-api:0.5.0'))
    // Approach #2: Depend on fabric-permissions-api, but require that users install it themselves
    implementation 'me.lucko:fabric-permissions-api:0.5.0'

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    api "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:26.1.3"
    
    // WorldEdit API for optional WorldEdit integration
    // compileOnlyApi "com.sk89q.worldedit:worldedit-fabric-mc${project.minecraft_version}:7.3.10-SNAPSHOT"
    // implementation "curse.maven:worldedit-225608:6013137"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}