plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    include(implementation("me.lucko:fabric-permissions-api:${fabric_permissions_api}"))
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    api "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcap_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}