# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Common
minecraft_version=1.21.5
mc_uuid=45c90175-34fa-4163-8d6a-0319bfb41d08
mc_username=Z0rdak
mc_accessToken=
version=0.5.3-beta3
versionType=beta
group=de.z0rdak.yawp
java_version=21
mod_name=Yet Another World Protector
mod_author=Z0rdak
mod_id=yawp
license=AGPL v3
description=Yet Another World Protector (YAWP) is a server-side mod to protect your creations. It was inspired by the forge mod WorldProtector and the WorldGuard plugin. Visit the discord server if you need help: https://discord.gg/d7hArKCUtm
resource_pack_desc=Internationalisation keys for Yet Another World Protector
credits=Thanks to all contributors (see CREDITS.txt)!

minecraft_version_range=[1.21.5, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830
# The ver
# sion of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.5
parchment_version=2025.06.15

# Fabric
fabric_version=0.128.1+1.21.5
fabric_loader_version=0.16.14

# Forge
forge_version=55.0.23
forge_loader_version_range=[55,)

# NeoForge
neoforge_version=21.5.82
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false