# Important Notes:
# Every field added must be added to the multiloader-common.gradle expandProps map.

# Common
java_version=21

# Misc
mc_uuid=45c90175-34fa-4163-8d6a-0319bfb41d08
mc_username=Z0rdak
mc_accessToken=

# Project
version=0.6.3-beta3
versionType=beta
group=de.z0rdak.yawp
mod_name=Yet Another World Protector
mod_author=Z0rdak
mod_id=yawp
license=AGPL v3
description=Yet Another World Protector (YAWP) is a server-side mod to protect your creations. It was inspired by the forge mod WorldProtector and the WorldGuard plugin. Visit the discord server if you need help: https://discord.gg/d7hArKCUtm
credits=Thanks to all contributors (see CREDITS.txt)!
resource_pack_desc=Internationalisation keys for Yet Another World Protector

curseforge_url=https://www.curseforge.com/minecraft/mc-mods/yawp
modrinth_url=https://modrinth.com/mod/yawp
wiki_url=https://z0rdak.github.io/yawp-docs/
update_url=

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=1.21.1
# https://minecraft.wiki/w/Pack_format#Resource_pack_format_history
resource_pack_format=[84]

# NeoForge, https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# https://projects.neoforged.net/neoforged/moddevgradle
neo_moddev_gradle=2.0.141

# The version of ParchmentMC that is used, see
# https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric, https://fabricmc.net/develop/
loader_version=0.19.2
loom_version=1.8-SNAPSHOT

# Fabric API
fabric_api_version=0.116.11+1.21.1
# Forge,
forge_version=52.1.14
forge_loader_version_range=[52,)

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.1.228
# https://projects.neoforged.net/neoforged/fancymodloader
neoforge_loader_version_range=[11,)

## Dependencies
# https://github.com/Fuzss/forgeconfigapiport
fcap_version=21.1.3

# Distribution
dist_curseforge_id=663276
dist_curseforge_slug=yawp
dist_github_slug=Yet-Another-World-Protector
dist_modrinth_id=py6EMmAJ
dist_modrinth_slug=yawp

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false