package de.z0rdak.yawp.commands;

public enum CommandConstants {
    ACTIVATE("activate"),
    ADD("add"),
    ADD_FLAG("add-flag"),
    ADD_OFFLINE("add-offline"),
    ADD_PLAYER("add-player"),
    ADD_TEAM("add-team"),
    GROUP("group"),
    ALERT("alert"),
    ALERT_LOCAL("alert-local"),
    MUTE("mute"),
    ALL("all"),
    ALLOW("allow"),

    AREA("area"),
    POS1("pos1"),
    POS2("pos2"),
    RADIUS_POS("radius-pos"),
    RADIUS("radius"),
    CENTER_POS("center-pos"),

    BLOCKS("blocks"),
    CHILD("child"),
    CHILDREN("children"),
    CLEAR("clear"),
    CREATE("create"),
    DEACTIVATE("deactivate"),
    DEC("-"),
    DEFAULT_Y("y-default"),
    DELETE("delete"),
    DELETE_ALL("delete-all"),
    FOREVER("forever"),
    SERIOUSLY("seriously"),
    DENY("deny"),
    DIM("dim"),
    TARGET_DIM("target-dim"),
    TARGET_REGION("target-region"),
    LOCAL("local"),
    TO_LOCAL("to-local"),
    TO_DIM("to-dim"),
    GLOBAL("global"),
    ENABLE("enable"),
    ENABLE_LOCAL("enable-local"),
    OVERRIDE("override"),
    EXPAND("expand"),
    FLAG("flag"),
    REGION_FLAG("region-flag"),
    FLAGS("flags"),
    ALL_FLAGS("all-flags"),
    FLAG_TYPE("flag-type"),
    FALSE("false"),
    TRUE("true"),
    HELP("help"),
    INC("+"),
    INFO("info"),
    COPY("copy"),
    LIST("list"),
    BOOL("bool"),
    INT("int"),
    MEMBER("member"),
    RENAME("rename"),
    NAME("name"),
    MARKER("marker"),
    GIVE("give"),
    OWNER("owner"),
    PARENT("parent"),
    PLAYER("player"),
    PLAYERS("players"),
    PLAYER_NAME("player-name"),
    PLAYER_NAMES("player-names"),
    BY_NAME("by-name"),
    PLAYER_UUIDS("player-uuids"),
    PLAYER_UUID("player-uuid"),
    BY_UUID("by-uuid"),
    PRIORITY("priority"),
    PAGE("page"),
    REGIONS("regions"),
    REMOVE("remove"),
    REMOVE_ALL("remove-all"),
    REMOVE_FLAG("remove-flag"),
    REMOVE_OFFLINE("remove-offline"),
    REMOVE_PLAYER("remove-player"),
    REMOVE_TEAM("remove-team"),
    RESET("reset"),
    SELECT("select"),
    SET("set"),
    SPATIAL("spatial"),
    STATE("state"),
    MSG("msg"),
    VALUE("value"),
    TARGET("target"),
    TEAM("team"),
    TEAMS("teams"),
    TELEPORT("tp"),
    TEMPLATE("template"),
    TRIGGER("trigger"),
    TYPE("type"),
    UPDATE("update"),
    VERT("vert"),
    EXPANSION("expansion"),
    Y_MIN("y-min"),
    Y_MAX("y-max");

    private final String cmdString;

    CommandConstants(final String cmdString) {
        this.cmdString = cmdString;
    }

    @Override
    public String toString() {
        return cmdString;
    }
}
