name: "Bug Report"
description: "Report a bug in the system"
title: "bug: [your-bug-title]"
labels: ["bug"]
body:

  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "Describe the bug in detail"
    validations:
      required: true

