name: Publish Mod

on: [ workflow_dispatch ]

permissions:
  contents: write  # Required for publishing

jobs:
  build:
    runs-on: ubuntu-latest
    # ...
    permissions:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: py6EMmAJ
          # modrinth-featured: true
          # modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 663276
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # github-tag: ${{ TODO version get here }}
          # github-commitish: ${{ source-branch= }}
          # github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            *build/libs/!(*-@(dev|sources|javadoc)).jar
            *build/libs/*-@(dev|sources|javadoc).jar
          
          #name: ${{ yawp-1.21.4-0.5.5-beta5 }} // Sodium 0.3.2 for Minecraft 1.17.1
          #version: ${{ mc1.17.1-0.3.2 TODO }} 
          #version-type: ${{ beta TODO }}
          #changelog-file: CHANGELOG.*
          #
          #java: |
          #  Java 21
          #
          #retry-attempts: 2
          #retry-delay: 10000
          #fail-mode: fail