name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss

      - name: Setup ENV
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      #- name: Copy Maven Upload URL
      #  id: extract_maven_upload_url
      #  run: echo "maven_upload_url=${{secrets.MAVEN_UPLOAD_URL}}" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew assemble

      #- name: Maven Release
      #  if: steps.extract_maven_upload_url.outputs.maven_upload_url
      #  env:
      #    BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
      #    BUILD_NUMBER: ${{ github.run_number }}
      #    MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
      #    MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
      #    MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
      #  run: ./gradlew publish

      #- name: Publish (GitHub Releases)
      #  uses: Kir-Antipov/mc-publish@v3.3
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    github-draft: false
      #    github-prerelease: false
      #    files: |
      #      **/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
      #      **/build/libs/*-@(sources|javadoc).jar

      #- name: Publish (NeoForge)
      #  uses: Kir-Antipov/mc-publish@v3.3
      #  with:
      #    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
      #    curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      #    version: ${{ github.ref_name }}-neoforge  # should resolve to <mc-version>-<mod-version>, e.g.: 1.21.4-0.5.2-beta1
      #    name:  yawp-${{ github.ref_name }}-neoforge # Sodium 0.3.2 for Minecraft 1.17.1
      #    changelog-file: changelog.*
      #    files: |
      #      neoforge/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
      #      neoforge/build/libs/*-@(sources|javadoc).jar

      #- name: Publish Forge to Curseforge
      #  uses: Kir-Antipov/mc-publish@v3.3
      #  with:
      #    curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      #    version: ${{ github.ref_name }}  # should resolve to <mc-version>-<mod-version>, e.g.: 1.21.4-0.5.2-beta1
      #    name:  1.20.1-${{ github.ref_name }}-forge # Sodium 0.3.2 for Minecraft 1.17.1
      #    changelog-file: changelogs/${{ github.ref_name }}.md
      #    files: |
      #      forge/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
      #      forge/build/libs/*-@(sources|javadoc).jar

      #- name: Publish Fabric to Curseforge
      #  uses: Kir-Antipov/mc-publish@v3.3
      #  with:
      #    curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      #    version: ${{ github.ref_name }}
      #    name: 1.20.1-${{ github.ref_name }}-fabric
      #    changelog-file: changelogs/${{ github.ref_name }}.md
      #    files: |
      #      fabric/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
      #      fabric/build/libs/*-@(sources|javadoc).jar

      - name: Publish Forge to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          version: ${{ github.ref_name }}  
          name:  1.20.1-${{ github.ref_name }}-forge
          changelog-file: changelogs/${{ github.ref_name }}.md
          files: |
            forge/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            forge/build/libs/*-@(sources|javadoc).jar

      - name: Publish Fabric to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          version: ${{ github.ref_name }} 
          name: 1.20.1-${{ github.ref_name }}-fabric
          changelog-file: changelogs/${{ github.ref_name }}.md
          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            fabric/build/libs/*-@(sources|javadoc).jar