name: Publish Mod

on: [ workflow_dispatch ]

permissions:
  contents: write  # Required for publishing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build Forge
        run: ./gradlew :forge:clean :forge:build
      
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: py6EMmAJ
          # modrinth-featured: true
          # modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 663276
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # github-tag: ${{ TODO version get here }}
          # github-commitish: ${{ source-branch= }}
          # github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            forge/build/libs/!(*-@(dev|sources|javadoc)).jar
            forge/build/libs/*-@(dev|sources|javadoc).jar
          
          #name: ${{ yawp-1.21.4-0.5.5-beta5 }} // Sodium 0.3.2 for Minecraft 1.17.1
          #version: ${{ mc1.17.1-0.3.2 TODO }} 
          #version-type: ${{ beta TODO }}
          #changelog-file: CHANGELOG.md
          #
          #java: |
          #  Java 21
          #
          #retry-attempts: 2
          #retry-delay: 10000
          #fail-mode: fail